### ISSUE TITLE
Firmware 2.0

### ISSUE THREAD

**Issue by peci1** [ctu-mrs/ouster#2]
It seems firmware 2.0 brings serious changes to the data format. If you have a less than 128-layer Ouster, check that this driver works with it correctly after updating firmware: https://data.ouster.io/downloads/software-user-manual/lidar-packet-format-update.pdf .

**Comment by pritzvac** [comment]
Closing the issue, we've just updated the driver to work with firmware 2.4, support for firmware < 2.0 was dropped.
